src/Entity/Horaire.php
<?php
namespace App\Entity;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * @ORM\Entity(repositoryClass="App\Repository\DisponibiliteRepository")
 */
class Horaires
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @var Prestataire
     * @ORM\OneToOne(targetEntity="prestataire", inversedBy="horaires")
     *
     * @ORM\JoinColumn(name="prestataire_id", referencedColumnName="id")
     */
    private $prestataire;
    /**
     * @ORM\Column(type="time", nullable=true)
     * @Assert\Time(message="Le format de l'heure n'est pas respecté")
     */
    private $lundi_ouverture;
    /**
     * @ORM\Column(type="time", nullable=true)
     * @Assert\Time(message="Le format de l'heure n'est pas respecté")
     */
    private $lundi_Fermeture;
    /**
     * @ORM\Column(type="time", nullable=true)
     * @Assert\Time(message="Le format de l'heure n'est pas respecté")
     */
    private $mardi_ouverture;
    /**
     * @ORM\Column(type="time", nullable=true)
     * @Assert\Time(message="Le format de l'heure n'est pas respecté")
     */
    private $mardi_fermeture;
    /**
     * @ORM\Column(type="time", nullable=true)
     * @Assert\Time(message="Le format de l'heure n'est pas respecté")
     */
    private $mercredi_ouverture;
    /**
     * @ORM\Column(type="time", nullable=true)
     * @Assert\Time(message="Le format de l'heure n'est pas respecté")
     */
    private $mercredi_fermeture;
    /**
     * @ORM\Column(type="time", nullable=true)
     * @Assert\Time(message="Le format de l'heure n'est pas respecté")
     */
    private $jeudi_ouverture;
    /**
     * @ORM\Column(type="time", nullable=true)
     * @Assert\Time(message="Le format de l'heure n'est pas respecté")
     */
    private $jeudi_fermeture;
    /**
     * @ORM\Column(type="time", nullable=true)
     * @Assert\Time(message="Le format de l'heure n'est pas respecté")
     */
    private $vendredi_ouverture;
    /**
     * @ORM\Column(type="time", nullable=true)
     * @Assert\Time(message="Le format de l'heure n'est pas respecté")
     */
    private $vendredi_fermeture;
    /**
     * @ORM\Column(type="time", nullable=true)
     * @Assert\Time(message="Le format de l'heure n'est pas respecté")
     */
    private $samedi_ouverture;
    /**
     * @ORM\Column(type="time", nullable=true)
     * @Assert\Time(message="Le format de l'heure n'est pas respecté")
     */
    private $samedi_fermeture;
    /**
     * @ORM\Column(type="time", nullable=true)
     * @Assert\Time(message="Le format de l'heure n'est pas respecté")
     */
    private $dimanche_ouverture;
    /**
     * @ORM\Column(type="time", nullable=true)
     * @Assert\Time(message="Le format de l'heure n'est pas respecté")
     */
    private $dimanche_fermeture;
    public function getId(): ?int
    {
        return $this->id;
    }
    /**
     * @return Prestataire
     */
    public function getPrestataire(): Prestataire
    {
        return $this->prestataire;
    }
    /**
     * @param Prestataire $prestataire
     * @return Horaires
     */
    public function setPrestataire(Prestataire $prestataire): Horaires
    {
        $this->prestataire = $prestataire;
        return $this;
    }
    /**
     * @return mixed
     */
    public function getLundiOuverture(): ?string
    {
        return $this->lundi_ouverture;
    }
    /**
     * @param mixed $lundi_ouverture
     * @return Horaires
     */
    public function setLundiOuverture($lundi_ouverture)
    {
        $this->lundi_ouverture = $lundi_ouverture;
        return $this;
    }
    /**
     * @return mixed
     */
    public function getLundiFermeture(): ?string
    {
        return $this->lundi_Fermeture;
    }
    /**
     * @param mixed $lundi_Fermeture
     * @return Horaires
     */
    public function setLundiFermeture($lundi_Fermeture)
    {
        $this->lundi_Fermeture = $lundi_Fermeture;
        return $this;
    }
    public function getMardiOuverture(): ?string
    {
        return $this->mardi_ouverture;
    }
    public function setMardiOuverture(?string $mardi_ouverture): self
    {
        $this->mardi_ouverture = $mardi_ouverture;
        return $this;
    }
    public function getMardiFermeture(): ?string
    {
        return $this->mardi_fermeture;
    }
    public function setMardiFermeture(?string $mardi_fermeture): self
    {
        $this->mardi_fermeture = $mardi_fermeture;
        return $this;
    }
    public function getMercrediOuverture(): ?string
    {
        return $this->mercredi_ouverture;
    }
    public function setMercrediOuverture(?string $mercredi_ouverture): self
    {
        $this->mercredi_ouverture = $mercredi_ouverture;
        return $this;
    }
    public function getMercrediFermeture(): ?string
    {
        return $this->mercredi_fermeture;
    }
    public function setMercrediFermeture(?string $mercredi_fermeture): self
    {
        $this->mercredi_fermeture = $mercredi_fermeture;
        return $this;
    }
    public function getJeudiOuverture(): ?string
    {
        return $this->jeudi_ouverture;
    }
    public function setJeudiOuverture(?string $jeudi_ouverture): self
    {
        $this->jeudi_ouverture = $jeudi_ouverture;
        return $this;
    }
    public function getJeudiFermeture(): ?string
    {
        return $this->jeudi_fermeture;
    }
    public function setJeudiFermeture(?string $jeudi_fermeture): self
    {
        $this->jeudi_fermeture = $jeudi_fermeture;
        return $this;
    }
    public function getVendrediOuverture(): ?string
    {
        return $this->vendredi_ouverture;
    }
    public function setVendrediOuverture(?string $vendredi_ouverture): self
    {
        $this->vendredi_ouverture = $vendredi_ouverture;
        return $this;
    }
    public function getVendrediFermeture(): ?string
    {
        return $this->vendredi_fermeture;
    }
    public function setVendrediFermeture(?string $vendredi_fermeture): self
    {
        $this->vendredi_fermeture = $vendredi_fermeture;
        return $this;
    }
    public function getSamediOuverture(): ?string
    {
        return $this->samedi_ouverture;
    }
    public function setSamediOuverture(?string $samedi_ouverture): self
    {
        $this->samedi_ouverture = $samedi_ouverture;
        return $this;
    }
    public function getSamediFermeture(): ?string
    {
        return $this->samedi_fermeture;
    }
    public function setSamediFermeture(?string $samedi_fermeture): self
    {
        $this->samedi_fermeture = $samedi_fermeture;
        return $this;
    }
    public function getDimancheOuverture(): ?string
    {
        return $this->dimanche_ouverture;
    }
    public function setDimancheOuverture(?string $dimanche_ouverture): self
    {
        $this->dimanche_ouverture = $dimanche_ouverture;
        return $this;
    }
    public function getDimancheFermeture(): ?string
    {
        return $this->dimanche_fermeture;
    }
    public function setDimancheFermeture(?string $dimanche_fermeture): self
    {
        $this->dimanche_fermeture = $dimanche_fermeture;
        return $this;
    }
}

src/Entity/Prestataire.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PrestataireRepository")
 * @Assert\GroupSequence({"Strict","Prestataire"})
 */
class Prestataire
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank(message="Le nom d'entreprise est obligatoire")
     */
    private $nom_entreprise;


    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="L' adresse est obligatoire")
     */
    private $adresse_entreprise;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank(message="La ville est obligatoire")
     */
    private $ville_entreprise;

    /**
     * @ORM\Column(type="string", length=5)
     * @Assert\NotBlank(message="Le code postale est obligatoire")
     * @Assert\Length(min="5", max="5", exactMessage="Le code postale ne doit pas dépasser {{ limit }} caractères")
     * @Assert\Type(type="digit", message="Le code postale doit contenir uniquement des chiffres")
     */
    private $cp_entreprise;

    /**
     * @ORM\Column(type="string", length=10)
     * @Assert\NotBlank(message="Le numero de téléhone est obligatoire")
     * @Assert\Length(min="10", max="10", exactMessage="Le numero de telephone doit contenir {{ limit }} de caractères ")
     * @Assert\Type(type="digit", message="Le N° de téléphone doit contenir uniquement des chiffres")
     */
    private $tel_entreprise;

     /**
     * @ORM\Column(type="array")
     * @Assert\NotBlank(message="Le lieu de prestation est obligatoire")
     * @Assert\Choice({"Chez le client", "Chez le prestataire", "En salon/institut"}, multiple=true, min="1", minMessage="Veuillez faire au minimum 1 choix de lieu" )
     */
    private $lieu_prestation;

    /**
     * @ORM\Column(type="string", length=14)
     * @Assert\NotBlank(message="Le n° SIRET est obligatoire")
     * @Assert\Length(max="14", min="14", maxMessage="Le n° SIRET ne doit pas dépasser {{ limit }} caractères")
     * @Assert\Type(type="digit", message="Le N° de siret doit contenir uniquement des chiffres")
     *
     */
    private $numero_siret;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Choice({"Validé", "En attente", "Refusé"})
     */
    private $certification;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Le fichier est obligatoire", groups={"Strict"})
     * @Assert\File(maxSize="2M", mimeTypesMessage="Le fichier doit être une image", groups={"Strict"})
     */
    private $cni;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description_entreprise;

    /**
     * @var Client
     * @ORM\OneToOne(targetEntity="Client", inversedBy="prestataire")
     * @ORM\JoinColumn(name="client_id", referencedColumnName="id")
     *
     */
    private $client;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Image(maxSize="2M", maxSizeMessage="Le fichier ne doit pas faire plus de 2Mo",
     * mimeTypesMessage="Le fichier doit être une image")
     */
    private $avatar;

    /**
     * @var Collection
     * @ORM\OneToMany(targetEntity="Photos", mappedBy="prestataire")
     */
    private $photo;

    /**
     * @ORM\Column(type="array")
     * @Assert\NotBlank(message="La profession est obligatoire")
     */
    private $profession;

    /**
     * @ORM\Column(type="simple_array", nullable=true)
     * @Assert\NotBlank(message="Les jours de disponibilités sont obligatoires", groups={"Strict"})
    */
    private $jour;

    /**
     * @var Collection
     * @ORM\OneToMany(targetEntity="Prestation", mappedBy="prestataire")
     */
    private $prestation;

    /**
     * @ORM\OneToOne(targetEntity="Horaires", inversedBy="prestataire", cascade={"persist"})
     * @ORM\JoinColumn(name="horaires_id", referencedColumnName="id")
     */
    private $horaires;

    /**
     * @return Collection
     */
    public function getPrestation(): Collection
    {
        return $this->prestation;
    }

    /**
     * @param Collection $prestation
     * @return Prestataire
     */
    public function setPrestation(Collection $prestation): Prestataire
    {
        $this->prestation = $prestation;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getHoraires()
    {
        return $this->horaires;
    }

    /**
     * @param mixed $horaires
     * @return Prestataire
     */
    public function setHoraires($horaires)
    {
        $this->horaires = $horaires;
        return $this;
    }

    public function __construct()
    {
        $this->photo = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getNomEntreprise()
    {
        return $this->nom_entreprise;
    }

    /**
     * @param mixed $nom_entreprise
     * @return Prestataire
     */
    public function setNomEntreprise($nom_entreprise)
    {
        $this->nom_entreprise = $nom_entreprise;
        return $this;
    }




    public function getAdresseEntreprise(): ?string
    {
        return $this->adresse_entreprise;
    }

    public function setAdresseEntreprise(string $adresse_entreprise): self
    {
        $this->adresse_entreprise = $adresse_entreprise;

        return $this;
    }

    public function getVilleEntreprise(): ?string
    {
        return $this->ville_entreprise;
    }

    public function setVilleEntreprise(string $ville_entreprise): self
    {
        $this->ville_entreprise = $ville_entreprise;

        return $this;
    }

    public function getCpEntreprise(): ?string
    {
        return $this->cp_entreprise;
    }

    public function setCpEntreprise(string $cp_entreprise): self
    {
        $this->cp_entreprise = $cp_entreprise;

        return $this;
    }

    public function getTelEntreprise(): ?string
    {
        return $this->tel_entreprise;
    }

    public function setTelEntreprise(string $tel_entreprise): self
    {
        $this->tel_entreprise = $tel_entreprise;

        return $this;
    }



    public function getLieuPrestation(): ?array
    {
        return $this->lieu_prestation;
    }

    public function setLieuPrestation(?array $lieu_presttion): self
    {
        $this->lieu_prestation = $lieu_presttion;

        return $this;
    }

    public function getNumeroSiret(): ?string
    {
        return $this->numero_siret;
    }

    public function setNumeroSiret(string $numero_siret): self
    {
        $this->numero_siret = $numero_siret;

        return $this;
    }

    public function getCertification(): ?string
    {
        return $this->certification;
    }

    public function setCertification(string $certification): self
    {
        $this->certification = $certification;

        return $this;
    }

    public function getCni()
    {
        return $this->cni;
    }

    public function setCni($cni): self
    {
        $this->cni = $cni;

        return $this;
    }

    public function getDescriptionEntreprise(): ?string
    {
        return $this->description_entreprise;
    }

    public function setDescriptionEntreprise(?string $description_entreprise): self
    {
        $this->description_entreprise = $description_entreprise;

        return $this;
    }

    /**
     * @return Client
     */
    public function getClient()
    {
        return $this->client;
    }

    /**
     * @param Client $client
     * @return Prestataire
     */
    public function setClient( $client): Prestataire
    {
        $this->client = $client;
        return $this;
    }

    /**
     * @return Collection
     */
    public function getPhoto(): Collection
    {
        return $this->photo;
    }

    /**
     * @param Collection $photo
     * @return Prestataire
     */
    public function setPhoto(Collection $photo): Prestataire
    {
        $this->photo = $photo;
        return $this;
    }


    /**
     * @return mixed
     */
    public function getProfession()
    {
        return $this->profession;
    }

    /**
     * @param mixed $profession
     * @return Prestataire
     */
    public function setProfession($profession)
    {
        $this->profession = $profession;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     * @param mixed $avatar
     * @return Prestataire
     */
    public function setAvatar($avatar)
    {
        $this->avatar = $avatar;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getJour()
    {
        return $this->jour;
    }

    /**
     * @param mixed $jour
     * @return Prestataire
     */
    public function setJour($jour)
    {
        $this->jour = $jour;
        return $this;
    }

    public function __toString()
    {
        return $this->nom_entreprise;
    }


}

src/Controller/AffichagePrestataireController.php
<?php

namespace App\Controller;

use App\Entity\Prestataire;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class AffichagePrestataireController extends AbstractController
{
    /**
     * @Route("/affichage/prestataire/{id}")
     */
    public function affichagePrestataire($id)
    {

        $em = $this->getDoctrine()->getManager();
        $prestataire = $em->find(Prestataire::class, $id);

        return $this->render('affichage_prestataire/index.html.twig',
            [
                'prestataire' => $prestataire,
            ]
        );
    }
}

templates/affichage_prestataire/index.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/affichage_prestataire.css') }}" />
    <link rel="stylesheet" href="{{ asset('css/slider.css') }}" />
{% endblock %}
 {% block body %}
     {% block header %}
         {{ parent() }}
     {% endblock %}
     {% block content %}
         <div class="container fiche_prestataire">
             <div class="result-content col-12">
             <div class="col-9 prestataire-infos ">
                 <h2>{{ prestataire.nomEntreprise}} {#- <span>{{ prestataire.villeEntreprise}}</span>#}</h2>
                 <h4><i class="fas fa-map-marker-alt"></i> {{ prestataire.adresseEntreprise}}, {{ prestataire.cpEntreprise}} {{ prestataire.villeEntreprise}}</h4>
                 <div class="col-12">

                     <div class="col-5 img_avatar">
                         <img src="{{ asset('img/' ~ prestataire.avatar) }}" alt="logo attente">
                     </div>


                     <div class="col-7 descrip-prestataire">
                         <p>{{ prestataire.descriptionEntreprise }}</p>
                     </div>
                 </div>
             </div>

             <div class="col-3 col-md-3 left-info">
                 <p><span>Type de profession</span>:<br> {{ prestataire.profession|join(' | ')}}</p>
                 <p><span>Lieu de prestation</span>:<br> {{ prestataire.lieuPrestation|join(' | ')}}</p>
                 <p class="jour-dispo"><span class="label-jour">Jour disponibles</span>:<br>
                     {% for jours in prestataire.jour %}
                         {% if jours == 1 %}
                             <span>Lundi</span>
                         {% elseif jours == 2 %}
                             <span>Mardi</span>
                         {% elseif jours == 3 %}
                             <span>Mercredi</span>
                         {% elseif jours == 4 %}
                             <span>Jeudi</span>
                         {% elseif jours == 5 %}
                             <span>Vendredi</span>
                         {% elseif jours == 6 %}
                             <span>Samedi</span>
                         {% elseif jours == 7 %}
                             <span>Dimanche</span>
                         {% endif%}
                     {% endfor %}
                 </p>
             </div>
             </div>
             <table class="table col-10 table-horaire">
                 <thead>
                    <tr>
                        <th>Jour</th>
                        <th>Ouverture</th>
                        <th>Fermeture</th>
                    </tr>
                 </thead>
                 <tbody>
                 {% for jour in prestataire.jour %}
                     {% if jour == 1  %}
                             <tr>
                                 <td>Lundi</td>
                                 <td>{{ prestataire.horaires.lundiOuverture|date('H:i') }}</td>
                                 <td>{{ prestataire.horaires.lundiFermeture|date('H:i') }}</td>
                             </tr>
                     {% elseif jour == 2  %}
                             <tr>
                                 <td>Mardi</td>
                                 <td>{{ prestataire.horaires.mardiOuverture|date('H:i') }}</td>
                                 <td>{{ prestataire.horaires.mardiFermeture|date('H:i') }}</td>
                             </tr>
                     {% elseif jour == 3  %}
                            <tr>
                                 <td>Mercredi</td>
                                 <td>{{ prestataire.horaires.mercrediOuverture|date('H:i') }}</td>
                                 <td>{{ prestataire.horaires.mercrediFermeture|date('H:i') }}</td>
                            </tr>
                     {% elseif jour == 4  %}
                            <tr>
                                 <td>Jeudi</td>
                                 <td>{{ prestataire.horaires.jeudiOuverture|date('H:i') }}</td>
                                 <td>{{ prestataire.horaires.jeudiFermeture|date('H:i') }}</td>
                            </tr>
                     {% elseif jour == 5  %}
                            <tr>
                                 <td>Vendredi</td>
                                 <td>{{ prestataire.horaires.vendrediOuverture|date('H:i') }}</td>
                                 <td>{{ prestataire.horaires.vendrediFermeture|date('H:i') }}</td>
                            </tr>
                     {% elseif jour == 6  %}
                            <tr>
                                 <td>Samedi</td>
                                 <td>{{ prestataire.horaires.samediOuverture|date('H:i') }}</td>
                                 <td>{{ prestataire.horaires.samediFermeture|date('H:i') }}</td>
                            </tr>
                     {% elseif jour == 7  %}
                            <tr>
                                <td>Dimanche</td>
                                <td>{{ prestataire.horaires.dimancheOuverture|date('H:i') }}</td>
                                <td>{{ prestataire.horaires.dimancheFermeture|date('H:i') }}</td>
                            </tr>
                     {% endif %}
                 {% endfor %}
                 </tbody>
             </table>
             <div class="slider col-10">
                 <div class="item" >
                     <ul id="content-slider" class="content-slider">
                         {% for photo in prestataire.photo %}
                             <li>
                                 <img src="{{ asset('img/' ~ photo.nom) }}" />
                             </li>
                         {% endfor %}
                     </ul>
                 </div>
             </div>
             <div class="col-10 prestation">
                 <h5>Nos prestations</h5>
                 {% for prestation in prestataire.prestation %}

                     <div>
                         <h6>
                             Nom de la prestation : {{ prestation.nom }}
                         </h6>
                         <p> Prix : {{ prestation.prix }}€</p>
                         <p> Durée : {{ prestation.duree|date('H:i') }}</p>
                         <p> Catégorie : {{ prestation.categorie }}</p>
                         <p> Description : {{ prestation.description }}</p>
                     </div>

                 {% endfor %}
             </div>
         </div>

     {% endblock %}
     {% block footer %}
         {{ parent() }}
     {% endblock %}
     {% block javascripts %}
         {{ parent() }}
         <!-- //Js -->
         <script src="{{ asset('js/slider.js') }}"></script>
     {% endblock %}
 {% endblock %}